// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteAPI.Data;

#nullable disable

namespace RestauranteAPI.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    partial class RestauranteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RestauranteAPI.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CuentaSolicitada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("RestauranteAPI.Models.OrdenDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePlatillo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("OrdenDetalles");
                });

            modelBuilder.Entity("RestauranteAPI.Models.Platillo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platillos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = "Platillos",
                            Destino = "cocina",
                            Nombre = "Enchiladas Suizas",
                            Precio = 85m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = "Platillos",
                            Destino = "cocina",
                            Nombre = "Tacos al Pastor",
                            Precio = 65m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = "Platillos",
                            Destino = "cocina",
                            Nombre = "Pozole",
                            Precio = 95m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = "Platillos",
                            Destino = "cocina",
                            Nombre = "Quesadillas",
                            Precio = 55m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Categoria = "Bebidas",
                            Destino = "barra",
                            Nombre = "Agua de Horchata",
                            Precio = 25m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Categoria = "Bebidas",
                            Destino = "barra",
                            Nombre = "Refresco",
                            Precio = 30m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Categoria = "Bebidas",
                            Destino = "barra",
                            Nombre = "Agua Natural",
                            Precio = 20m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Categoria = "Bebidas",
                            Destino = "barra",
                            Nombre = "Cerveza",
                            Precio = 45m
                        });
                });

            modelBuilder.Entity("RestauranteAPI.Models.OrdenDetalle", b =>
                {
                    b.HasOne("RestauranteAPI.Models.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("RestauranteAPI.Models.Orden", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
